### ISSUE TITLE
Won't compile ARMV7

### ISSUE THREAD

**Issue by CartridgeGen** [Yabause/yabause#291]
Hello, I'm trying to compile yabause but whatever configuration I choose is giving me this error : 
`[  3%] Built target c68kinc
Scanning dependencies of target yabause
[  4%] [  4%] [  5%] [  5%] Building C object src/CMakeFiles/yabause.dir/memory.c.o
Building C object src/CMakeFiles/yabause.dir/profile.c.o
Building C object src/CMakeFiles/yabause.dir/scu.c.o
Building C object src/CMakeFiles/yabause.dir/scspdsp.c.o
[  6%] Building C object src/CMakeFiles/yabause.dir/sh2core.c.o
/media/My_Passport/sat/yabause/yabause/src/memory.c: In function ‘MappedMemoryInit’:
/media/My_Passport/sat/yabause/yabause/src/memory.c:694:45: error: ‘Sh2SoundRamReadByte’ undeclared (first use in this function)
       FillMemoryArea(sh2[i], 0x5A0, 0x5AF, &Sh2SoundRamReadByte,
                                             ^
/media/My_Passport/sat/yabause/yabause/src/memory.c:694:45: note: each undeclared identifier is reported only once for each function it appears in
/media/My_Passport/sat/yabause/yabause/src/memory.c:695:45: error: ‘Sh2SoundRamReadWord’ undeclared (first use in this function)
                                            &Sh2SoundRamReadWord,
                                             ^
/media/My_Passport/sat/yabause/yabause/src/memory.c:696:45: error: ‘Sh2SoundRamReadLong’ undeclared (first use in this function)
                                            &Sh2SoundRamReadLong,
                                             ^
/media/My_Passport/sat/yabause/yabause/src/memory.c:697:45: error: ‘Sh2SoundRamWriteByte’ undeclared (first use in this function)
                                            &Sh2SoundRamWriteByte,
                                             ^
/media/My_Passport/sat/yabause/yabause/src/memory.c:698:45: error: ‘Sh2SoundRamWriteWord’ undeclared (first use in this function)
                                            &Sh2SoundRamWriteWord,
                                             ^
/media/My_Passport/sat/yabause/yabause/src/memory.c:699:45: error: ‘Sh2SoundRamWriteLong’ undeclared (first use in this function)
                                            &Sh2SoundRamWriteLong);
                                             ^
/media/My_Passport/sat/yabause/yabause/src/memory.c:700:45: error: ‘Sh2ScspReadByte’ undeclared (first use in this function)
       FillMemoryArea(sh2[i], 0x5B0, 0x5BF, &Sh2ScspReadByte,
                                             ^
/media/My_Passport/sat/yabause/yabause/src/memory.c:701:45: error: ‘Sh2ScspReadWord’ undeclared (first use in this function)
                                            &Sh2ScspReadWord,
                                             ^
/media/My_Passport/sat/yabause/yabause/src/memory.c:702:45: error: ‘Sh2ScspReadLong’ undeclared (first use in this function)
                                            &Sh2ScspReadLong,
                                             ^
/media/My_Passport/sat/yabause/yabause/src/memory.c:703:45: error: ‘Sh2ScspWriteByte’ undeclared (first use in this function)
                                            &Sh2ScspWriteByte,
                                             ^
/media/My_Passport/sat/yabause/yabause/src/memory.c:704:45: error: ‘Sh2ScspWriteWord’ undeclared (first use in this function)
                                            &Sh2ScspWriteWord,
                                             ^
/media/My_Passport/sat/yabause/yabause/src/memory.c:705:45: error: ‘Sh2ScspWriteLong’ undeclared (first use in this function)
                                            &Sh2ScspWriteLong);
                                             ^
src/CMakeFiles/yabause.dir/build.make:353: recipe for target 'src/CMakeFiles/yabause.dir/memory.c.o' failed
make[2]: *** [src/CMakeFiles/yabause.dir/memory.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
`

What is wrong? I've never seen this error before in yabause. Weird.
Compiling with GCC5.3 on Linux Debian Jessie.

**Comment by d356** [comment]
It's not really clear why those functions would be undeclared, have you tried a fresh checkout and deleting CMakeCache.txt?

**Comment by CartridgeGen** [comment]
Yes I've tried using a fresh clone and I've tried deleting CMakeCache.txt.
If for any reason that you need this information, I'm trying to compile with GCC 5.3.0
using -static-libstdc++ as stranger flag, I think it looks much like this issue here that has been resolved
https://github.com/Yabause/yabause/issues/276 but for ARM instead of X86. On 0.9.13 of yabause, I'm getting invalid use of restrict. I'm aware I have to use the sed command to fix it but I don't remember how to do it. Back to 0.9.15, should I give a long-version log for you to check out?

**Comment by d356** [comment]
Thanks for the log, could I also see what options you've configured cmake with? If you're using YAB_USE_SCSP2 I think that's probably the issue.

**Comment by CartridgeGen** [comment]
That seems to have done the trick. But why would it not compile with SCSP2 while on 0.9.13 I have it included? What has changed that much about SCSP? I'm still compiling at the moment but each time I restart the compilation, features I used in 0.9.13 I'm removing them 1 by 1. Q68, SCSP. Those are the two I've removed so far. I may be mistaken about SCSP if I included it or not but IIRC I did compile that in. Yabause has been my best for Saturn since 0.9.13 and I'd love more compatibility for ARM with the features you've included like MPEG,SSF,M68K. I'd love to have those as it's more accurate to the Hardware. GLES would be the nicest thing ever happened to Yabause but let's not ask too much for now. Having an update of any kind about Yabause is very well welcomed.

**Comment by d356** [comment]
The SCSP was rewritten to have better quality sound after 9.13, I believe Guillaume and CyberWarriorX are planning to remove the SCSP2.

The SSF player and Musashi both work on my ARM device. MPEG support isn't finished yet.

linkage_arm is from the SH2 dynarec, which is not going to work correctly even if the compile error is fixed. You can try going back to a previous revision or if you're specifically interested in ARM and OpenGL ES you might want to try this branch: https://github.com/devmiyax/yabause

**Comment by CartridgeGen** [comment]
Thanks! But that fork looks me that extui is the most updated one and is not merged with "master".
Can you confirm that it's version 0.9.14? I've been looking through it and it seems to me that it is .14

Thank you so much for your great help and pointing me in the right direction. That does not mean that I won't be looking at this "Original Source" for updates! Nothing better than original.

**Comment by CartridgeGen** [comment]
It's not compiling and with errors I can't fix. I'll stick to 0.9.13 until a new original build is available.

**Comment by d356** [comment]
It's a fork and has a mix of changes from the main branch and his own work, so it doesn't directly correspond to Yabause's version numbers and doesn't have every change from the main branch. If you're getting compile errors you'll have to ask the author of the fork about them.
